### ISSUE TITLE
Add configuration in `/config/general.toml`

### ISSUE THREAD

**Issue by JosiahBull** [JosiahBull/festival-api#13]
# Description
Load configuration options from `/src/general.toml`, with several fallbacks along the way. This should make configuration easier.

# Tasks/General Thoughts
- [x] Pull from environment first
- [x] ~~Pull from .env?~~ - Massive increase in complexity + extra dependencies. Doesn't make a lot of sense to do this any configuration situation where we want to read from .env we can reasonably expect the user to put those items actually into the environment.
- [x] Pull from `/src/general.toml`
- [x] ~~Pull from `./Rocket.toml`~~ - Same reason as above, just not worth it. `/src/general.toml` handles all we need.
- [x] Write documentation that makes it clear what each item does.
