### ISSUE TITLE
Add metadata tags on downloaded files

### ISSUE THREAD

**Issue by JosiahBull** [JosiahBull/festival-api#14]
## Description
Downloaded files should have their metadata tags set, so that operating systems will display the relevant information about the file.

## Tasks/General Thoughts
- [ ] Work for converted or original files (of all types)
- [ ] Could use https://crates.io/crates/audiotags
- [ ] Minimal Overhead (benchmark it)
