### ISSUE TITLE
More Endpoints

### ISSUE THREAD

**Issue by JosiahBull** [JosiahBull/festival-api#20]
## Description
We need more account endpoints so that users are able to easily get information about their account. 
We also want more endpoints so users can discover supported languages, allowed chars, etc on the api.

## Tasks/General Thoughts
- [ ] User account info.
- [ ] Time till able to make requests.
- [ ] Number of words left in rate limit.
- [ ] Allowed Chars
- [ ] Supported Langs
- [ ] Allowed Formats
- [ ] Phrase Length Limit
- [ ] OAS Docs
- [ ] Readme
