### ISSUE TITLE
Refactor Codebase

### ISSUE THREAD

**Issue by JosiahBull** [JosiahBull/festival-api#22]
## Description
Currently the codebase is very monolithic and disorganized. To move forward in a productive manner it will be a good idea to reorganise code. This is a fairly substantial task without a lot of immediate benefit.

In terms of modules, I'm currently thinking
- Database - Handle all db interactions, we can migrate a lot of `common.rs` here.
- Auth - Handle JWT's, and eventually cookies etc.
- Cache - TBD, will be done in #5 
- Response - Migrate `response.rs`
- Config - All lazy statics, and related macros should be migrated. Can also take this opportunity to move duplicate code into functions.

Can also migrate tests into other modules, especially e2e tests currently in `main.rs` can go into `./tests/*`

At the same time we should refactor `lazy_static` to wrap in `RwLock` - this will allow easy modification for testing purposes. 

## Tasks/General Thoughts
- [x] Create a proper workspace, with a library and submodules.
- [x] Split off modules
- [x] Wrap global statics in `RwLock` to allow modification for testing purposes
- [x] Split off tests
- [x] Fix dockerfiles & readme
