### ISSUE TITLE
Windows and Macos Deployment Support

### ISSUE THREAD

**Issue by JosiahBull** [JosiahBull/festival-api#25]
## Description
For development, users should be able to run this api on macos. As macos is unix based, I don't imagine this port will be too hard to achieve.

With that note, the ability to run this api on windows 10/11 should be considered. I suppose we could achieve this with WSL, but that is quite a bit of installation/configuration. 
From reading it appears that [festival](http://festvox.org/festival/) and [ffmpeg](https://www.ffmpeg.org/download.html) are available for windows install - albeit not *quite* as stable as on unix based systems. 
We will need to ensure support for both Windows 10 and 11.

Uninstall scripts should also be provided.

Note that while I have access to a mac, I am not overly familiar with the platform. If someone else with development experience on macos wishes to handle the scripts for that I would be very appreciative.

## Tasks/General Thoughts
- [ ] Install/setup script for Linux (Ubuntu 20.04/Ubuntu 21.04/Fedora 34/Fedora 35)
- [ ] Install/setup script for Mac (Big Sur)
  - [ ] https://github.com/pettarin/setup-festival-mbrola
- [ ] Install/setup script for Windows 10 & Windows 11
- [ ] Updating readme
- [ ] Reduce reliance on docker (can we spawn the postgres instance independently?)
- [ ] Replace Sox dependency with Ffmpeg, if that doesn't occur with #14
