### ISSUE TITLE
Check configuration on launch.

### ISSUE THREAD

**Issue by JosiahBull** [JosiahBull/festival-api#6]
## Description
When the program starts, we should validate that all configuration options from config are valid.

This could even be done as a simple bash script which runs `cargo test`.

## Tasks/General Thoughts
- [ ] Validate general config
- [ ] Test festival is working
- [ ] Check database setup

**Comment by JosiahBull** [comment]
This will not be implemented. After further thought, imposing hard limits on what values can be set could cause problems for fringe users of the api.

We should instead provide ample documentation and resources, and they rely on users to configure their settings properly.
