### ISSUE TITLE
Improve security of bash underlying the project

### ISSUE THREAD

**Issue by JosiahBull** [JosiahBull/festival-api#9]
# Description
The current implementation for generating `wav` files is vulnerable to a RCE attack. Limiting the charset + properly implementing `std::process::Command` in main would be a good idea.

# Tasks/General Thoughts
- [x] Remove invalid chars from `PhrasePackage`'s sent by the user.
- [x] Fix `std::process::Command` to be safe.
- [x] Simple test to validate that the issue is fixed.
